# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: kvstore.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.client
import grpclib.const

if typing.TYPE_CHECKING:
    import grpclib.server

import kvstore_pb2


class KeyValueStoreBase(abc.ABC):

    @abc.abstractmethod
    async def Put(
        self,
        stream: "grpclib.server.Stream[kvstore_pb2.PutRequest, kvstore_pb2.PutResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def Get(
        self,
        stream: "grpclib.server.Stream[kvstore_pb2.GetRequest, kvstore_pb2.GetResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def Delete(
        self,
        stream: "grpclib.server.Stream[kvstore_pb2.DeleteRequest, kvstore_pb2.DeleteResponse]",
    ) -> None:
        pass

    @abc.abstractmethod
    async def List(
        self,
        stream: "grpclib.server.Stream[kvstore_pb2.ListRequest, kvstore_pb2.ListResponse]",
    ) -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            "/kvstore.KeyValueStore/Put": grpclib.const.Handler(
                self.Put,
                grpclib.const.Cardinality.UNARY_UNARY,
                kvstore_pb2.PutRequest,
                kvstore_pb2.PutResponse,
            ),
            "/kvstore.KeyValueStore/Get": grpclib.const.Handler(
                self.Get,
                grpclib.const.Cardinality.UNARY_UNARY,
                kvstore_pb2.GetRequest,
                kvstore_pb2.GetResponse,
            ),
            "/kvstore.KeyValueStore/Delete": grpclib.const.Handler(
                self.Delete,
                grpclib.const.Cardinality.UNARY_UNARY,
                kvstore_pb2.DeleteRequest,
                kvstore_pb2.DeleteResponse,
            ),
            "/kvstore.KeyValueStore/List": grpclib.const.Handler(
                self.List,
                grpclib.const.Cardinality.UNARY_UNARY,
                kvstore_pb2.ListRequest,
                kvstore_pb2.ListResponse,
            ),
        }


class KeyValueStoreStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Put = grpclib.client.UnaryUnaryMethod(
            channel,
            "/kvstore.KeyValueStore/Put",
            kvstore_pb2.PutRequest,
            kvstore_pb2.PutResponse,
        )
        self.Get = grpclib.client.UnaryUnaryMethod(
            channel,
            "/kvstore.KeyValueStore/Get",
            kvstore_pb2.GetRequest,
            kvstore_pb2.GetResponse,
        )
        self.Delete = grpclib.client.UnaryUnaryMethod(
            channel,
            "/kvstore.KeyValueStore/Delete",
            kvstore_pb2.DeleteRequest,
            kvstore_pb2.DeleteResponse,
        )
        self.List = grpclib.client.UnaryUnaryMethod(
            channel,
            "/kvstore.KeyValueStore/List",
            kvstore_pb2.ListRequest,
            kvstore_pb2.ListResponse,
        )
