# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

import kvstore_pb2 as kvstore__pb2

GRPC_GENERATED_VERSION = "1.81.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in kvstore_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class KeyValueStoreStub:
    """KeyValueStore — in-memory хранилище ключ–значение с TTL и LRU eviction.
    Контракт менять нельзя. Реализуйте серверную часть.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
            "/kvstore.KeyValueStore/Put",
            request_serializer=kvstore__pb2.PutRequest.SerializeToString,
            response_deserializer=kvstore__pb2.PutResponse.FromString,
            _registered_method=True,
        )
        self.Get = channel.unary_unary(
            "/kvstore.KeyValueStore/Get",
            request_serializer=kvstore__pb2.GetRequest.SerializeToString,
            response_deserializer=kvstore__pb2.GetResponse.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/kvstore.KeyValueStore/Delete",
            request_serializer=kvstore__pb2.DeleteRequest.SerializeToString,
            response_deserializer=kvstore__pb2.DeleteResponse.FromString,
            _registered_method=True,
        )
        self.List = channel.unary_unary(
            "/kvstore.KeyValueStore/List",
            request_serializer=kvstore__pb2.ListRequest.SerializeToString,
            response_deserializer=kvstore__pb2.ListResponse.FromString,
            _registered_method=True,
        )


class KeyValueStoreServicer:
    """KeyValueStore — in-memory хранилище ключ–значение с TTL и LRU eviction.
    Контракт менять нельзя. Реализуйте серверную часть.
    """

    def Put(self, request, context):
        """Put: добавить или обновить значение. ttl_seconds = 0 означает отсутствие TTL."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Get(self, request, context):
        """Get: получить значение по ключу. NOT_FOUND — если ключ отсутствует или TTL истёк."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """Delete: удалить ключ."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List(self, request, context):
        """List: вернуть все ключи и значения с данным prefix. Истёкшие по TTL не возвращать."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Put": grpc.unary_unary_rpc_method_handler(
            servicer.Put,
            request_deserializer=kvstore__pb2.PutRequest.FromString,
            response_serializer=kvstore__pb2.PutResponse.SerializeToString,
        ),
        "Get": grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=kvstore__pb2.GetRequest.FromString,
            response_serializer=kvstore__pb2.GetResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=kvstore__pb2.DeleteRequest.FromString,
            response_serializer=kvstore__pb2.DeleteResponse.SerializeToString,
        ),
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=kvstore__pb2.ListRequest.FromString,
            response_serializer=kvstore__pb2.ListResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "kvstore.KeyValueStore", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("kvstore.KeyValueStore", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class KeyValueStore:
    """KeyValueStore — in-memory хранилище ключ–значение с TTL и LRU eviction.
    Контракт менять нельзя. Реализуйте серверную часть.
    """

    @staticmethod
    def Put(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/kvstore.KeyValueStore/Put",
            kvstore__pb2.PutRequest.SerializeToString,
            kvstore__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Get(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/kvstore.KeyValueStore/Get",
            kvstore__pb2.GetRequest.SerializeToString,
            kvstore__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/kvstore.KeyValueStore/Delete",
            kvstore__pb2.DeleteRequest.SerializeToString,
            kvstore__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/kvstore.KeyValueStore/List",
            kvstore__pb2.ListRequest.SerializeToString,
            kvstore__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
